organizationNames:
    source: "MODIFY THIS TEXT TO MATCH THE NAME OF YOUR SOURCE ORGANIZATION"
    destination: "MODIFY THIS TEXT TO MATCH THE NAME OF YOUR DESTINATION ORGANIZATION"
    
enabledTasks:
    createNetworks: true
    refreshTimeZones: true
    copyMxVlans: true
    copyMrSsids: true
    copyMrFirewallRules: true
    copyAlerts: true
    
configModifications:
    overwriteSsidRadiusSecret:
        enabled: true
        newRadiusSecret: "superSecret"
    overwriteSiteToSiteVpnHub:
        enabled: false
        oldHubNetworkName: "MODIFY THIS TEXT TO MATCH HUB NET NAME IN SOURCE ORG"
        newHubNetworkName: "MODIFY THIS TEXT TO MATCH HUB NET NAME IN DESTINATION ORG"
    ipConflictVlanTempSubnetPrefix: "1.1.1."
        
networkFilters:
    filterSourceNetworksByTag: false
    sourceNetworkTagsList:
        - "process-this"
        
    excludeTargetNetworksByTag: false
    targetNetworkTagsList:
        - "do-not-process"